'use client'
import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import './assets/globals.scss'
import Header from '@/components/main/header/header'
import React from 'react'
import {ThemeProvider} from '@/components/option/theme-provider'
import {useAppStore} from '@/store/app'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const {isDrawerOpen} = useAppStore((state) => state)
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <main
            className={`w-full flex flex-col gap-0 relative ${isDrawerOpen ? 'drawer-open' : ''}`}>
            <Header />
            <div className="flex w-full flex-col app-main">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
