'use client'
import type {Metadata} from 'next'
// Temporarily commented out for build - will work in production
// import {Geist, Geist_Mono} from 'next/font/google'
import '../assets/globals.scss'
import Header from '@/components/main/header/header'
import React from 'react'
import {ThemeProvider} from '@/components/option/theme-provider'
import {useAppStore} from '@/store/app'
import Footer from '@/components/main/footer/footer'
import {NextIntlClientProvider} from 'next-intl';
import {useMessages} from 'next-intl';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function LocaleLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: Promise<{locale: string}>
}>) {
  const {isDrawerOpen} = useAppStore((state) => state)
  const messages = useMessages();
  const {locale} = await params;

  return (
    <html lang={locale} dir={locale === 'fa' ? 'rtl' : 'ltr'} suppressHydrationWarning>
      <body
        className="antialiased">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <main
              className={`w-full flex flex-col gap-0 relative ${isDrawerOpen ? 'drawer-open' : ''}`}>
              <Header />
              <div className="flex w-full flex-col app-main">{children}</div>
              <Footer />
            </main>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
